license="All Rights Reserved"

#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="aq_icon.png"
credits="MarbledHubb Studios"
authors="MarbledNull, Aimiwi, WereF0X"

description='''
A mod that allows the player to bring back ancient life from past time periods
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
